import type { ExtensionContext } from "vscode";
import type { LoggingService } from "@/infrastructure/services/logging/LoggingService";
import type { VSCodeFileSystemService } from "@/infrastructure/services/filesystem/VSCodeFileSystemService";
import type { ExtensionContextStorageService } from "@/infrastructure/services/storage/ExtensionContextStorageService";
import type { CachingService } from "@/infrastructure/services/caching/CachingService";
import type { PerformanceMonitorService } from "@/infrastructure/services/performance/PerformanceMonitorService";
import type { GenerationCacheService } from "@/infrastructure/services/caching/GenerationCacheService";
import type { RequestBatchingService } from "@/infrastructure/services/optimization/RequestBatchingService";
import type { DebouncingService } from "@/infrastructure/services/optimization/DebouncingService";
import type { BackgroundProcessingService } from "@/infrastructure/services/optimization/BackgroundProcessingService";
import type { MemoryOptimizationService } from "@/infrastructure/services/optimization/MemoryOptimizationService";
import type { VSCodeApiKeyRepository } from "@/infrastructure/repositories/VSCodeApiKeyRepository";
import type { VSCodeConfigurationRepository } from "@/infrastructure/repositories/VSCodeConfigurationRepository";
import type { ErrorHandlerImpl } from "@/infrastructure/services/error/ErrorHandler";
import type { ErrorLoggingService } from "@/infrastructure/services/error/ErrorLoggingService";
import type { ErrorRecoveryService } from "@/infrastructure/services/error/ErrorRecoveryService";
import type { SelectionService } from "@/application/services/core/SelectionService";
import type { CommandRegistry } from "@/application/CommandRegistry";
import type { WikiStorageService } from "@/application/services/storage/WikiStorageService";
import type { LLMRegistry } from "@/llm";
import type { WikiService } from "@/application/services/core/WikiService";
import type { CachedWikiService } from "@/application/services/core/CachedWikiService";
import type { SelectionEventHandler } from "@/events/handlers/SelectionEventHandler";
import type { WikiEventHandler } from "@/events/handlers/WikiEventHandler";
import type { WikiWatcherService } from "@/infrastructure/services/storage/WikiWatcherService";
import type { ConfigurationManagerService } from "@/application/services/configuration/ConfigurationManagerService";
import type { ConfigurationValidationEngineService } from "@/application/services/configuration/ConfigurationValidationEngineService";
import type { ConfigurationTemplateService } from "@/application/services/configuration/ConfigurationTemplateService";
import type { ContextAnalysisService } from "@/application/services/context/ContextAnalysisService";
import type { CachedProjectContextService } from "@/application/services/context/project/CachedProjectContextService";
import type { ProjectContextService } from "@/application/services/context/project/ProjectContextService";
import type { CodeExtractionService } from "@/application/services/context/relevance/CodeExtractionService";
import type { ContextCompressionService } from "@/application/services/context/ContextCompressionService";
import type { ContextIntelligenceService } from "@/application/services/context/ContextIntelligenceService";
import type { PromptQualityService } from "@/application/services/prompts/PromptQualityService";
import type { AdvancedPromptService } from "@/application/services/prompts/AdvancedPromptService";
import type { LLMProviderFactory } from "@/factories/LLMProviderFactory";
import type { SmartProviderSelectionService } from "@/application/services/providers/SmartProviderSelectionService";
import type { ProviderSelectionService } from "@/application/services/providers/ProviderSelectionService";
import type { ProviderValidationService } from "@/infrastructure/services/providers/ProviderValidationService";
import type { ProviderFallbackManagerService } from "@/application/services/providers/ProviderFallbackManagerService";
import type { EventBus } from "@/events/EventBus";
import type { SecretStorage } from "vscode";

export interface ServiceRegistry {
  loggingService: LoggingService;
  vscodeFileSystemService: VSCodeFileSystemService;
  context: ExtensionContext;
  secrets: SecretStorage;
  extensionContextStorageService: ExtensionContextStorageService;
  cachingService: CachingService;
  performanceMonitor: PerformanceMonitorService;
  generationCacheService: GenerationCacheService;
  requestBatchingService: RequestBatchingService;
  debouncingService: DebouncingService;
  backgroundProcessingService: BackgroundProcessingService;
  memoryOptimizationService: MemoryOptimizationService;
  apiKeyRepository: VSCodeApiKeyRepository;
  configurationRepository: VSCodeConfigurationRepository;
  errorHandler: ErrorHandlerImpl;
  errorLoggingService: ErrorLoggingService;
  errorRecoveryService: ErrorRecoveryService;
  selectionService: SelectionService;
  commandRegistry: CommandRegistry;
  wikiStorageService: WikiStorageService;
  llmRegistry: LLMRegistry;
  wikiService: WikiService;
  cachedWikiService: CachedWikiService;
  selectionEventHandler: SelectionEventHandler;
  wikiEventHandler: WikiEventHandler;
  wikiWatcherService: WikiWatcherService;
  configurationManager: ConfigurationManagerService;
  configurationValidationEngine: ConfigurationValidationEngineService;
  configurationTemplateService: ConfigurationTemplateService;
  contextAnalysisService: ContextAnalysisService;
  cachedProjectContextService: CachedProjectContextService;
  projectContextService: ProjectContextService;
  codeExtractionService: CodeExtractionService;
  contextCompressionService: ContextCompressionService;
  contextIntelligenceService: ContextIntelligenceService;
  promptQualityService: PromptQualityService;
  advancedPromptService: AdvancedPromptService;
  llmProviderFactory: LLMProviderFactory;
  providerSelectionService: ProviderSelectionService;
  providerValidationService: ProviderValidationService;
  providerFallbackManager: ProviderFallbackManagerService;
  eventBus: EventBus;
}

export type ServiceKey = keyof ServiceRegistry;
