import type { ConfigurationTemplate } from "@/domain/configuration";

export function createMultiProviderPreset(): ConfigurationTemplate {
  return {
    id: "multi-provider",
    name: "Multi-Provider Setup",
    description: "Configure multiple providers with intelligent fallback",
    category: "enterprise",
    configuration: {
      global: {
        defaultProviderId: "google-ai-studio",
        autoGenerateWiki: true,
        wikiOutputFormat: "markdown",
        maxContextLength: 6000,
        enableCaching: true,
        cacheExpirationHours: 12,
        enablePerformanceMonitoring: true,
        enableErrorReporting: true,
        logLevel: "info",
        uiTheme: "auto",
        language: "en",
        autoSave: true,
        backupEnabled: true,
        backupRetentionDays: 60,
      },
      providers: {
        "google-ai-studio": {
          id: "google-ai-studio",
          name: "Google AI Studio",
          enabled: true,
          model: "gemini-2.5-flash",
          temperature: 0.2,
          maxTokens: 4096,
          rateLimitPerMinute: 40,
          timeout: 20000,
          retryAttempts: 3,
          fallbackProviderIds: ["zai", "openrouter"],
        },
        zai: {
          id: "zai",
          name: "Z.ai",
          enabled: true,
          model: "glm-4.6",
          temperature: 0.3,
          maxTokens: 3072,
          rateLimitPerMinute: 60,
          timeout: 18000,
          retryAttempts: 2,
          fallbackProviderIds: ["openrouter", "cohere"],
        },
        openrouter: {
          id: "openrouter",
          name: "OpenRouter",
          enabled: true,
          model: "qwen/qwen3-coder:free",
          temperature: 0.4,
          maxTokens: 2048,
          rateLimitPerMinute: 50,
          timeout: 15000,
          retryAttempts: 2,
          fallbackProviderIds: ["cohere", "huggingface"],
        },
        cohere: {
          id: "cohere",
          name: "Cohere",
          enabled: false,
          model: "command-r7b-12-2024",
          temperature: 0.3,
          maxTokens: 2048,
          rateLimitPerMinute: 40,
          timeout: 22000,
          retryAttempts: 2,
          fallbackProviderIds: ["huggingface"],
        },
        huggingface: {
          id: "huggingface",
          name: "Hugging Face",
          enabled: false,
          model: "Qwen/Qwen3-8B",
          temperature: 0.5,
          maxTokens: 1536,
          rateLimitPerMinute: 25,
          timeout: 25000,
          retryAttempts: 1,
        },
      },
    },
    metadata: {
      author: "Qwiki",
      version: "1.0.0",
      tags: ["multi-provider", "fallback", "resilience", "enterprise"],
      compatibleProviders: ["google-ai-studio", "zai", "openrouter", "cohere", "huggingface"],
    },
  };
}
