import type { Command } from "./Command";
import type { EventBus } from "../../events";
import { WikiStorageService } from "../../wiki/services/WikiStorageService";
import { WikiStatus } from "../../wiki/types/WikiTypes";

export interface CreateWikiPagePayload {
  title: string;
  content: string;
  projectId: string;
  tags?: string[];
  category?: string;
  metadata?: {
    author?: string;
    status?: string;
    priority?: string;
  };
}

export class CreateWikiPageCommand implements Command<CreateWikiPagePayload> {
  constructor(
    private eventBus: EventBus,
    private wikiStorageService: WikiStorageService
  ) {}

  async execute(payload: CreateWikiPagePayload): Promise<void> {
    try {
      const page = {
        id: '', // Will be generated by service
        title: payload.title,
        content: payload.content,
        tags: payload.tags || [],
        relationships: [],
        metadata: {
          createdAt: new Date(),
          updatedAt: new Date(),
          author: payload.metadata?.author || 'system',
          version: 1,
          status: (payload.metadata?.status as WikiStatus) || WikiStatus.DRAFT,
          projectId: payload.projectId,
          category: payload.category || 'general',
          priority: payload.metadata?.priority || 'medium'
        }
      };

      const pageId = await this.wikiStorageService.createWikiPage(page);

      await this.eventBus.publish('wikiPageCreated', {
        pageId,
        page: { ...page, id: pageId },
        projectId: payload.projectId
      });
    } catch (error) {
      await this.eventBus.publish('error', {
        message: `Failed to create wiki page: ${(error as Error).message}`,
        code: 'CREATE_WIKI_PAGE_ERROR',
        suggestion: 'Check if the content and title are valid'
      });
      throw error;
    }
  }
}