import type { Command } from "./Command";
import type { EventBus } from "../../events";
import { PromptTemplateService } from "../../prompts/services/PromptTemplateService";
import { PromptCategory, PromptComplexity } from "../../prompts/types/PromptTypes";

export interface CreatePromptTemplatePayload {
  name: string;
  content: string;
  variables?: Array<{
    name: string;
    type: string;
    description: string;
    required: boolean;
    defaultValue?: string;
  }>;
  metadata?: {
    category: PromptCategory;
    language: string;
    provider: string;
    complexity: PromptComplexity;
    effectiveness?: number;
  };
}

export class CreatePromptTemplateCommand implements Command<CreatePromptTemplatePayload> {
  constructor(
    private eventBus: EventBus,
    private promptTemplateService: PromptTemplateService
  ) {}

  async execute(payload: CreatePromptTemplatePayload): Promise<void> {
    try {
      const template = {
        id: '', // Will be generated by service
        name: payload.name,
        version: '1.0.0',
        content: payload.content,
        variables: payload.variables || [],
        metadata: {
          category: payload.metadata?.category || PromptCategory.Custom,
          language: payload.metadata?.language || 'en',
          provider: payload.metadata?.provider || 'generic',
          complexity: payload.metadata?.complexity || PromptComplexity.Moderate,
          effectiveness: payload.metadata?.effectiveness
        }
      };

      const templateId = await this.promptTemplateService.createTemplate(template);

      await this.eventBus.publish('promptTemplateCreated', {
        templateId,
        template: { ...template, id: templateId }
      });
    } catch (error) {
      await this.eventBus.publish('error', {
        message: `Failed to create prompt template: ${(error as Error).message}`,
        code: 'CREATE_TEMPLATE_ERROR',
        suggestion: 'Check if all required fields are provided and valid'
      });
      throw error;
    }
  }
}