export const ErrorCodes = {
  PROVIDER_NOT_FOUND: "PROVIDER_NOT_FOUND",
  API_KEY_MISSING: "API_KEY_MISSING",
  API_KEY_INVALID: "API_KEY_INVALID",
  MODEL_NOT_SUPPORTED: "MODEL_NOT_SUPPORTED",
  NETWORK_ERROR: "NETWORK_ERROR",
  RATE_LIMIT_EXCEEDED: "RATE_LIMIT_EXCEEDED",
  GENERATION_FAILED: "GENERATION_FAILED",
  VALIDATION_ERROR: "VALIDATION_ERROR",
  CONFIGURATION_ERROR: "CONFIGURATION_ERROR",
  PROVIDER_NOT_SELECTED: "PROVIDER_NOT_SELECTED",
  MISSING_SNIPPET: "MISSING_SNIPPET",
  INIT_TIMEOUT: "INIT_TIMEOUT",
} as const;

export type ErrorCode = (typeof ErrorCodes)[keyof typeof ErrorCodes];
