export const ErrorCodes = {
  unknown: "error.unknown",
  generationFailed: "error.generationFailed",
  invalidSelection: "error.invalidSelection",
  missingSnippet: "error.missingSnippet",
  missingProvider: "error.missingProvider",
  invalidConfiguration: "error.invalidConfiguration",
  missingCommand: "error.missingCommand",
  apiKeyMissing: "error.apiKeyMissing",
  apiKeyInvalid: "error.apiKeyInvalid",
  invalidModel: "error.invalidModel",
  providerDisabled: "error.providerDisabled",
  customFieldMissing: "error.customFieldMissing",
  providerNotConfigured: "error.providerNotConfigured",
  validationFailed: "error.validationFailed",
  noApiKeysConfigured: "error.noApiKeysConfigured",
  apiKeyHealthCheckFailed: "error.apiKeyHealthCheckFailed",
  apiKeyHealthCheckTimeout: "error.apiKeyHealthCheckTimeout",
  providerNoHealthCheck: "error.providerNoHealthCheck",
  readmeUpdateFailed: "error.readme.updateFailed",
  readmeUndoFailed: "error.readme.undoFailed",
  savedWikisLoadFailed: "error.savedWikis.loadFailed",
  savedWikisLoadTimeout: "error.savedWikis.loadTimeout",
  savedWikisDeleteFailed: "error.savedWikis.deleteFailed",
  notificationError: "error.notification",
  rateLimitExceeded: "error.rateLimitExceeded",
} as const;

export const ErrorMessages = {
  [ErrorCodes.unknown]: "Unknown error",
  [ErrorCodes.generationFailed]: "Generation failed",
  [ErrorCodes.invalidSelection]: "Invalid selection",
  [ErrorCodes.missingSnippet]: "No code selected",
  [ErrorCodes.missingProvider]: "Provider not available",
  [ErrorCodes.invalidConfiguration]: "Invalid configuration",
  [ErrorCodes.missingCommand]: "Command not found",
  [ErrorCodes.apiKeyMissing]: "API key is required",
  [ErrorCodes.apiKeyInvalid]: "API key is invalid",
  [ErrorCodes.invalidModel]: "Model is not available",
  [ErrorCodes.providerDisabled]: "Provider is disabled",
  [ErrorCodes.customFieldMissing]: "Custom field is missing",
  [ErrorCodes.providerNotConfigured]: "Provider is not configured",
  [ErrorCodes.validationFailed]: "Validation failed",
  [ErrorCodes.noApiKeysConfigured]: "At least one API key is required for the extension to work",
  [ErrorCodes.apiKeyHealthCheckFailed]: "Unable to verify API key - connection failed",
  [ErrorCodes.apiKeyHealthCheckTimeout]: "API key validation timed out",
  [ErrorCodes.providerNoHealthCheck]: "Unable to validate API key for this provider",
  [ErrorCodes.readmeUpdateFailed]: "Failed to update README",
  [ErrorCodes.readmeUndoFailed]: "Failed to undo README update",
  [ErrorCodes.savedWikisLoadFailed]: "Failed to load saved wikis",
  [ErrorCodes.savedWikisLoadTimeout]: "Saved wikis request timed out",
  [ErrorCodes.savedWikisDeleteFailed]: "Failed to delete saved wiki",
  [ErrorCodes.notificationError]: "Operation failed",
  [ErrorCodes.rateLimitExceeded]: "Rate limit exceeded",
} as const;

