export const CommandIds = {
  generateWiki: "generateWiki",
  getSelection: "getSelection",
  getRelated: "getRelated",
  saveApiKey: "saveApiKey",
  getProviders: "getProviders",
  openFile: "openFile",
  openExternal: "openExternal",
  saveSetting: "saveSetting",
  deleteApiKey: "deleteApiKey",
  getApiKeys: "getApiKeys",
  getProviderConfigs: "getProviderConfigs",
  getProviderCapabilities: "getProviderCapabilities",
  getConfiguration: "getConfiguration",
  updateConfiguration: "updateConfiguration",
  validateConfiguration: "validateConfiguration",
  applyConfigurationTemplate: "applyConfigurationTemplate",
  createConfigurationBackup: "createConfigurationBackup",
  getProviderHealth: "getProviderHealth",
  getProviderPerformance: "getProviderPerformance",
  saveWiki: "saveWiki",
  getSavedWikis: "getSavedWikis",
  deleteWiki: "deleteWiki",
  createAggregation: "createAggregation",
  updateReadme: "updateReadme",
  previewReadmeUpdate: "previewReadmeUpdate",
  getAggregations: "getAggregations",
} as const;

export const VSCodeCommandIds = {
  showPanel: "qwiki.show",
  viewSettings: "qwiki.viewSettings",
  viewSavedWikis: "qwiki.viewSavedWikis",
  viewErrorHistory: "qwiki.viewErrorHistory",
  createQuickWiki: "qwiki.createQuickWiki",
  createWikiAggregation: "qwiki.createWikiAggregation",
  updateReadme: "qwiki.updateReadme",
  openPanelView: "workbench.view.extension.qwiki",
  wikiViewId: "qwiki.wikiView",
} as const;
