export const CommandIds = {
  generateWiki: "generateWiki",
  getSelection: "getSelection",
  getRelated: "getRelated",
  saveApiKey: "saveApiKey",
  getProviders: "getProviders",
  openFile: "openFile",
  openExternal: "openExternal",
  saveSetting: "saveSetting",
  deleteApiKey: "deleteApiKey",
  getApiKeys: "getApiKeys",
  getProviderConfigs: "getProviderConfigs",
  getProviderCapabilities: "getProviderCapabilities",
  getConfiguration: "getConfiguration",
  updateConfiguration: "updateConfiguration",
  validateConfiguration: "validateConfiguration",
  applyConfigurationTemplate: "applyConfigurationTemplate",
  getConfigurationTemplates: "getConfigurationTemplates",
  createConfigurationBackup: "createConfigurationBackup",
  getConfigurationBackups: "getConfigurationBackups",
  getProviderHealth: "getProviderHealth",
  getProviderPerformance: "getProviderPerformance",
  saveWiki: "saveWiki",
  getSavedWikis: "getSavedWikis",
  deleteWiki: "deleteWiki",
  updateReadme: "updateReadme",
} as const;

export const VSCodeCommandIds = {
  showPanel: "qwiki.show",
  viewSettings: "qwiki.viewSettings",
  viewSavedWikis: "qwiki.viewSavedWikis",
  viewErrorHistory: "qwiki.viewErrorHistory",
  createQuickWiki: "qwiki.createQuickWiki",
  selectProvider: "qwiki.selectProvider",
  openPanelView: "workbench.view.extension.qwiki",
  wikiViewId: "qwiki.wikiView",
} as const;
