export const ErrorCodes = {
  unknown: "error.unknown",
  generationFailed: "error.generationFailed",
  invalidSelection: "error.invalidSelection",
  missingSnippet: "error.missingSnippet",
  missingProvider: "error.missingProvider",
  invalidConfiguration: "error.invalidConfiguration",
  missingCommand: "error.missingCommand",
  apiKeyMissing: "error.apiKeyMissing",
  apiKeyInvalid: "error.apiKeyInvalid",
  invalidModel: "error.invalidModel",
  providerDisabled: "error.providerDisabled",
  customFieldMissing: "error.customFieldMissing",
  providerNotConfigured: "error.providerNotConfigured",
  validationFailed: "error.validationFailed",
  noApiKeysConfigured: "error.noApiKeysConfigured",
  apiKeyHealthCheckFailed: "error.apiKeyHealthCheckFailed",
  apiKeyHealthCheckTimeout: "error.apiKeyHealthCheckTimeout",
  providerNoHealthCheck: "error.providerNoHealthCheck",
} as const;

export const ErrorMessages = {
  [ErrorCodes.unknown]: "Unknown error",
  [ErrorCodes.generationFailed]: "Generation failed",
  [ErrorCodes.invalidSelection]: "Invalid selection",
  [ErrorCodes.missingSnippet]: "No code selected",
  [ErrorCodes.missingProvider]: "Provider not available",
  [ErrorCodes.invalidConfiguration]: "Invalid configuration",
  [ErrorCodes.missingCommand]: "Command not found",
  [ErrorCodes.apiKeyMissing]: "API key is required",
  [ErrorCodes.apiKeyInvalid]: "API key is invalid",
  [ErrorCodes.invalidModel]: "Model is not available",
  [ErrorCodes.providerDisabled]: "Provider is disabled",
  [ErrorCodes.customFieldMissing]: "Custom field is missing",
  [ErrorCodes.providerNotConfigured]: "Provider is not configured",
  [ErrorCodes.validationFailed]: "Validation failed",
  [ErrorCodes.noApiKeysConfigured]: "At least one API key is required for the extension to work",
  [ErrorCodes.apiKeyHealthCheckFailed]: "Unable to verify API key - connection failed",
  [ErrorCodes.apiKeyHealthCheckTimeout]: "API key validation timed out",
  [ErrorCodes.providerNoHealthCheck]: "Unable to validate API key for this provider",
} as const;

export const ErrorTitles = {
  [ErrorCodes.unknown]: "Unknown Error",
  [ErrorCodes.generationFailed]: "Generation Failed",
  [ErrorCodes.invalidSelection]: "Invalid Selection",
  [ErrorCodes.missingSnippet]: "No Code Selected",
  [ErrorCodes.missingProvider]: "Provider Not Available",
  [ErrorCodes.invalidConfiguration]: "Invalid Configuration",
  [ErrorCodes.missingCommand]: "Command Not Found",
  [ErrorCodes.apiKeyMissing]: "API Key Required",
  [ErrorCodes.apiKeyInvalid]: "Invalid API Key",
  [ErrorCodes.invalidModel]: "Model Not Available",
  [ErrorCodes.providerDisabled]: "Provider Disabled",
  [ErrorCodes.customFieldMissing]: "Custom Field Missing",
  [ErrorCodes.providerNotConfigured]: "Provider Not Configured",
  [ErrorCodes.validationFailed]: "Validation Failed",
  [ErrorCodes.noApiKeysConfigured]: "No API Keys Configured",
  [ErrorCodes.apiKeyHealthCheckFailed]: "API Key Health Check Failed",
  [ErrorCodes.apiKeyHealthCheckTimeout]: "API Key Validation Timeout",
  [ErrorCodes.providerNoHealthCheck]: "Provider Health Check Unavailable",
} as const;
