export const InboundEvents = {
  webviewReady: "webviewReady",
  getSelection: "getSelection",
  getRelated: "getRelated",
  openFile: "openFile",
  saveApiKey: "saveApiKey",
  deleteApiKey: "deleteApiKey",
  getProviders: "getProviders",
  getProviderConfigs: "getProviderConfigs",
  getApiKeys: "getApiKeys",
  generateWiki: "generateWiki",
  saveSetting: "saveSetting",
  createPromptTemplate: "createPromptTemplate",
  updatePromptTemplate: "updatePromptTemplate",
  deletePromptTemplate: "deletePromptTemplate",
  getPromptTemplate: "getPromptTemplate",
  getAllPromptTemplates: "getAllPromptTemplates",
  renderPromptTemplate: "renderPromptTemplate",
  validatePrompt: "validatePrompt",
  scorePromptQuality: "scorePromptQuality",
  optimizePromptForProvider: "optimizePromptForProvider",
  createPromptVariant: "createPromptVariant",
  getPromptVariants: "getPromptVariants",
  createWikiPage: "createWikiPage",
  updateWikiPage: "updateWikiPage",
  deleteWikiPage: "deleteWikiPage",
  getWikiPage: "getWikiPage",
  getAllWikiPages: "getAllWikiPages",
  searchWikiPages: "searchWikiPages",
  aggregateWikis: "aggregateWikis",
  generateProjectWiki: "generateProjectWiki",
  createWikiLink: "createWikiLink",
  getWikiLinks: "getWikiLinks",
  generateCrossReferences: "generateCrossReferences",
  getRelatedWikiPages: "getRelatedWikiPages",
  buildWikiIndex: "buildWikiIndex",
  getWikiIndex: "getWikiIndex",
  getWikiStatistics: "getWikiStatistics",
  createWikiVersion: "createWikiVersion",
  getWikiVersions: "getWikiVersions",
  revertWikiVersion: "revertWikiVersion",
  calculateQualityMetrics: "calculateQualityMetrics",
  scoreQuality: "scoreQuality",
  generateQualityReport: "generateQualityReport",
  trackQualityTrend: "trackQualityTrend",
  suggestImprovements: "suggestImprovements",
  createImprovementPlan: "createImprovementPlan",
  applyImprovement: "applyImprovement",
  prioritizeSuggestions: "prioritizeSuggestions",
  trackImprovementProgress: "trackImprovementProgress",
  runQAChecks: "runQAChecks",
  createQAWorkflow: "createQAWorkflow",
  validateAgainstStandards: "validateAgainstStandards",
  approveContent: "approveContent",
  rejectContent: "rejectContent",
} as const;

export const OutboundEvents = {
  navigate: "navigate",
  webviewReady: "webviewReady",
  selection: "selection",
  triggerGenerate: "triggerGenerate",
  loadingStep: "loadingStep",
  wikiResult: "wikiResult",
  error: "error",
  related: "related",
  apiKeySaved: "apiKeySaved",
  apiKeyDeleted: "apiKeyDeleted",
  providers: "providers",
  providerConfigs: "providerConfigs",
  apiKeys: "apiKeys",
  settingSaved: "settingSaved",
} as const;

export const LoadingSteps = {
  validating: "validating",
  analyzing: "analyzing",
  finding: "finding",
  preparing: "preparing",
  buildingPrompt: "buildingPrompt",
  sendingRequest: "sendingRequest",
  waitingForResponse: "waitingForResponse",
  processing: "processing",
  finalizing: "finalizing",
} as const;

export type LoadingStep = (typeof LoadingSteps)[keyof typeof LoadingSteps];

export const ErrorEvents = {
  occurred: "error.occurred",
  recoveryAttempt: "error.recoveryAttempt",
  recoverySuccess: "error.recoverySuccess",
  recoveryFailed: "error.recoveryFailed",
} as const;

export const Pages = {
  wiki: "wiki",
  settings: "settings",
  promptManager: "promptManager",
  wikiAggregator: "wikiAggregator",
  qualityDashboard: "qualityDashboard",
} as const;

export type Page = (typeof Pages)[keyof typeof Pages];
