export const FilePatterns = {
  exclude: "**/{node_modules,dist,out,build,.git,.vscode,_refs,tmp,temp}/**",
  excludeWithoutVscode: "**/{node_modules,dist,out,build,_refs,tmp,temp}/**",
  excludeBinary: "**/*.{png,jpg,jpeg,gif,ico,svg,pdf,zip,tar,gz,exe,dll,so,dylib}",
  excludeLarge: "**/*.min.{js,css}",
  excludeBackups: "**/*.{backup,bak,old}",
  sourceFiles: "**/*.{ts,tsx,js,jsx,py,java,go,rs,php,rb,cs,swift,kt}",
  configFiles: "**/*.{json,yml,yaml,toml,xml,ini,conf}",
  packageJson: "package.json",
  srcAlias: "src/",
  allFiles: "**/*",

  excludeDirectories: [
    "node_modules",
    "bower_components",
    "vendor",
    "jspm_packages",
    ".pnpm",
    "dist",
    "out",
    "build",
    "_build",
    ".output",
    ".next",
    ".nuxt",
    ".svelte-kit",
    ".vercel",
    ".netlify",
    ".git",
    ".svn",
    ".hg",
    ".vscode",
    ".idea",
    ".vs",
    ".cache",
    ".parcel-cache",
    ".turbo",
    "tmp",
    "temp",
    "_refs",
    ".temp",
    ".tmp",
    "__pycache__",
    ".pytest_cache",
    ".mypy_cache",
    ".tox",
    ".eggs",
    "*.egg-info",
    "coverage",
    ".nyc_output",
    ".coverage",
    "htmlcov",
    ".other-repos",
    ".external",
    "_external",
    "submodules",
    "logs",
    ".logs",
    "*.log",
  ],

  excludeFilePatterns: [
    "yarn.lock",
    "package-lock.json",
    "pnpm-lock.yaml",
    "composer.lock",
    "Cargo.lock",
    "Gemfile.lock",
    "poetry.lock",
    "*.min.js",
    "*.min.css",
    "*.bundle.js",
    "*.chunk.js",
    "*.pyc",
    "*.pyo",
    "*.pyd",
    "*.class",
    "*.o",
    "*.obj",
    "*.so",
    "*.dll",
    "*.dylib",
    "*.exe",
    "*.bin",
    "*.png",
    "*.jpg",
    "*.jpeg",
    "*.gif",
    "*.ico",
    "*.svg",
    "*.webp",
    "*.bmp",
    "*.tiff",
    "*.pdf",
    "*.doc",
    "*.docx",
    "*.xls",
    "*.xlsx",
    "*.ppt",
    "*.pptx",
    "*.zip",
    "*.tar",
    "*.gz",
    "*.rar",
    "*.7z",
    "*.bz2",
    "*.mp3",
    "*.mp4",
    "*.wav",
    "*.avi",
    "*.mov",
    "*.wmv",
    "*.flv",
    "*.webm",
    "*.woff",
    "*.woff2",
    "*.ttf",
    "*.eot",
    "*.otf",
    "*.map",
    "*.d.ts.map",
    "*.backup",
    "*.bak",
    "*.old",
    "*.orig",
    "*~",
  ],
} as const;

export const FileLimits = {
  projectFiles: 200,
  relatedFiles: 400,
  maxRelatedResults: 50,
  maxFileSample: 50,
  maxDependencies: 10,
  maxDevDependencies: 5,
} as const;
