<template>
  <svg
    class="h-3 w-3 flex-shrink-0 sm:h-4 sm:w-4"
    viewBox="0 0 24 24"
    xmlns="http://www.w3.org/2000/svg"
    aria-hidden="true"
    focusable="false"
  >
    <DotShape fill="url(#qwikiAnimatedGradient)">
      <animate
        id="spinner_FFyM"
        begin="0;spinner_HDCY.end"
        attributeName="x"
        dur="0.2s"
        values="1;13"
        fill="freeze"
      />
      <animate
        id="spinner_AIvE"
        begin="spinner_1FwE.end"
        attributeName="y"
        dur="0.2s"
        values="1;13"
        fill="freeze"
      />
      <animate
        id="spinner_wWCL"
        begin="spinner_gH4o.end"
        attributeName="x"
        dur="0.2s"
        values="13;1"
        fill="freeze"
      />
      <animate
        id="spinner_S3Gg"
        begin="spinner_Q0bx.end"
        attributeName="y"
        dur="0.2s"
        values="13;1"
        fill="freeze"
      />
    </DotShape>
    <DotShape fill="url(#qwikiAnimatedGradient)" x="1" y="13">
      <animate
        id="spinner_1FwE"
        begin="spinner_FFyM.end"
        attributeName="y"
        dur="0.2s"
        values="13;1"
        fill="freeze"
      />
      <animate
        id="spinner_gH4o"
        begin="spinner_AIvE.end"
        attributeName="x"
        dur="0.2s"
        values="1;13"
        fill="freeze"
      />
      <animate
        id="spinner_Q0bx"
        begin="spinner_wWCL.end"
        attributeName="y"
        dur="0.2s"
        values="1;13"
        fill="freeze"
      />
      <animate
        id="spinner_HDCY"
        begin="spinner_S3Gg.end"
        attributeName="x"
        dur="0.2s"
        values="13;1"
        fill="freeze"
      />
    </DotShape>
  </svg>
</template>

<script setup lang="ts">
import DotShape from "./DotShape.vue";
</script>
